# Generated by Django 3.2.6 on 2021-08-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('match_id', models.FloatField(null=True, primary_key=True, serialize=False)),
                ('match', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'matches',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('player_id', models.FloatField(null=True, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'players',
                'managed': False,
            },
        ),
    ]
