# Generated by Django 3.2.6 on 2021-09-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl2021', '0002_auto_20210901_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdetails',
            options={},
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='passwrd',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='userdetails',
            old_name='name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
